---
title: "JSM Program"
output: html_document
date: "2025-06-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(stringr)
library(dplyr)
library(timevis)
library(htmltools)
library(tidyr)

```

```{r}
html <- read_html("https://ww3.aievolution.com/JSMAnnual2025/Events/pubSearchEvents?style=0")
rows = html %>% html_elements("tr")
headerIDs = which(rows %>% html_attr("id")  == "_dateHeader")
```

```{r}
str_strip <- function(s) {
  s %>% str_replace_all("\r", "") %>% str_replace_all("\t", "") %>% 
    str_replace_all("^ ", "") %>% str_replace_all("  $", "") %>% str_replace_all(" ", " ") %>% 
    str_replace_all("javascript:previewEvent\\(","") %>% str_replace_all("\\);","")
}
```


```{r}
DF = data.frame()
pb <- progress::progress_bar$new(total = length(headerIDs))
for(iDay in seq_along(headerIDs)) {
  dateRow = headerIDs[iDay]
  day = rows[[dateRow]] %>% html_text2() %>% str_strip
  minRow = headerIDs[iDay] + 2
  maxRow = ifelse(iDay < length(headerIDs), headerIDs[iDay+1] - 2, length(rows)-1)
  for(i in minRow:maxRow) {
    id = rows[[i]] %>% html_elements(".action") %>% html_element("a") %>% html_attr("href") %>% str_strip
    time = rows[[i]] %>%  html_children() %>% html_text2() %>% .[2] %>% str_strip
    title = rows[[i]] %>%  html_children() %>% html_text2() %>% .[3] %>% str_strip
    type = rows[[i]] %>%  html_children() %>% html_text2() %>% .[4] %>% str_strip
    df_ = data.frame(id = id, time = time, title = title, type = type, day = day)
    DF = rbind(DF, df_)
  }
  pb$tick()
}
```

```{r}
write.csv(DF, "./time_table.csv", row.names = FALSE)
```



```{r}

```



```{r}
```

```{r}
style <- "
  .vis-timeline {
    font-size: 13px;
  }
"
```


```{r}
data_ <- DF %>% filter(day == unique(DF$day)[4]) %>% 
  filter(type == "Contributed Papers ")
  # filter(type == "Invited Paper Session ")
data <- data_  %>% 
  separate_wider_delim(time, delim = " - ", names = c("start", "end")) %>% 
  transmute(id = 1:nrow(.), start, end, title) %>% 
  mutate(title  = gsub("\\n", "<br>", str_wrap(title, width = 30))) # Adjust width as needed



tv = timevis(data.frame(
  id = data$id, start = paste("2025-08-01 ", data$start), end =  paste("2025-08-01 ", data$end), content = data$title
))
tv <- tagList(tags$style(style), tv)

# Print or display the timeline
htmltools::html_print(tv)
```


```{r}
data <- data.frame(
  id      = 1:4,
  content = c("Item one"  , "Item two"  ,"Ranged item", "Item four"),
  start   = c("2016-01-10", "2016-01-11", "2016-01-20", "2016-02-14 15:00:00"),
  end     = c(NA          ,           NA, "2016-02-04", NA)
)

timevis(data, height = "100px")
```

