---
title: "Load Event"
output: html_document
date: "2025-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(stringr)
library(dplyr)
library(timevis)
library(htmltools)
library(tidyr)
```

```{r}
id = 2880
prefix = "https://ww3.aievolution.com/JSMAnnual2025/Events/viewEv?ev="
html <- read_html(paste0(prefix, id))
```

```{r}
title <- html %>% html_element("h1") %>% html_text2()
cat(title)
```

```{r}
room <- html %>% html_elements("#eventPreview_roomAssignments") %>% html_text2()
room <- trimws(strsplit(room, ":")[[1]][2])
room
```

```{r}
titles <- html %>% html_elements(".presentation-title")
titles %>% length
```

```{r}
descs <- html_elements(html, ".presentationPreview_description")
descs %>% length
```

```{r}
presentations <- html %>% html_elements(".eventlevelthree")
```

```{r}
html %>% html_element(".presesntaionspeakers") %>% html_element(xpath = "..")
```
```{r}
speakers <- html %>% html_elements(".presesntaionspeakers")
sp1 = speakers[1] %>% html_element(xpath = "..")
new_html <- read_html(paste0(as.character(sp1), collapse = ""))
new_html %>% html_elements(".speakername") %>% html_text2() %>% unique
```


```{r}
sp2 = speakers[2] %>% html_element(xpath = "..")
```

```{r}
as.character(sp1) == as.character(sp2)
```
```{r}
char_speakers <- c()
for(i in 1:length(speakers)) {
  char_speakers <- append(char_speakers, as.character(speakers[i] %>% html_element(xpath = "..")))
}
html_speakers <- lapply(unique(char_speakers), read_html)
```

```{r}
html_speakers[[3]] %>% html_elements(".speakername") %>% html_text2() %>% unique %>% paste(collapse = ", ")
```

```{r}
descs[3] %>% html_text2()
```
```{r}
DF <- data.frame()
for(i in 1:length(titles)) {
  title = gsub("\\r","", html_text2(titles[i]) )
  speakers <- html_speakers[[i]] %>% html_elements(".speakername") %>% html_text2() %>% unique %>% paste(collapse = ", ")
  df_ <- data.frame(
    title = trimws(title),
    speakers = trimws(speakers),
    room = room
    )
  DF <- bind_rows(DF, df_)
}
DF
```

```{r}
write.csv(DF, paste0("./jsm_shiny/events/", id, ".csv"), row.names = FALSE)
```

```{r}
load_section_info <- function(id, prefix = "https://ww3.aievolution.com/JSMAnnual2025/Events/viewEv?ev=") {
  file_name <-  paste0("./jsm_shiny/events/", id, ".csv")
  if(file.exists(file_name)) {
    return( read.csv(file_name))
  }
  cat("webscraping info")
  html <- read_html(paste0(prefix, id))
  room <- html %>% html_elements("#eventPreview_roomAssignments") %>% html_text2()
  room <- trimws(strsplit(room, ":")[[1]][2])
  titles <- html %>% html_elements(".presentation-title")
  speakers <- html %>% html_elements(".presesntaionspeakers")
  char_speakers <- c()
  for(i in 1:length(speakers)) {
    char_speakers <- append(char_speakers, as.character(speakers[i] %>% html_element(xpath = "..")))
  }
  html_speakers <- lapply(unique(char_speakers), read_html)
  DF <- data.frame()
  for(i in 1:length(titles)) {
    title = gsub("\\r","", html_text2(titles[i]) )
    speakers <- html_speakers[[i]] %>% html_elements(".speakername") %>% html_text2() %>% unique %>% paste(collapse = ", ")
    df_ <- data.frame(
      title = trimws(title),
      speakers = trimws(speakers),
      room = room
      )
    DF <- bind_rows(DF, df_)
  }
  write.csv(DF, file_name, row.names = FALSE)
  return(DF)
}
load_section_info(id)
```

```{r}
load_section_info(2825)
```

